### ISSUE TITLE
Encounters are not loading

### ISSUE THREAD

**Issue by laurendukes** [verilylifesciences/medtimeline#16]
First step of this bug is to add better logging for why the encounters are not loading.

Suggest putting the x-request-id in the hover text for the warning icon for encounter loading and contacting Cerner for further debugging, since everything looks like it's loading ok in BUILD.

**Comment by laurendukes** [comment]
This work is similar to issue #12 in that I think the first step here is getting the request ID. 

The work should be broken out into a separate PR since it isn't in a card like the other requests.

There are two places this error should get surfaced.
1) In the setup screen, we load encounters so that we can let users pick from them as their initial time window. If we don't get encounters at that point, we should a) surface an always-viewable error that says something like "Problem loading encounters. Request ID: ...", and also a drop-down expander similar to the cards that provides the call stack.

2) In the app, beside the datepicker, we show a little error triangle beside the date field if we can't read the encounters. On hover, we should surface the request ID there too, along with the short error text that's already there. (No need to put the call stack here.)

Replication and testing should be similar to #12.

**Comment by hilarymulholland** [comment]
I think we can close this since it seems as if it is a data issue. @laurendukes feel free to re-open if you think this has been closed pre-maturely.
